# Form implementation generated from reading ui file 'arduinosettings.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from config.config import *

class Arduino_settings(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(376, 100)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(280, 30, 81, 51))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.line_baud = QtWidgets.QLineEdit(parent=Dialog)
        self.line_baud.setGeometry(QtCore.QRect(10, 20, 251, 20))
        self.line_baud.setAutoFillBackground(False)
        self.line_baud.setText("9600")
        self.line_baud.setClearButtonEnabled(False)
        self.line_baud.setObjectName("line_baud")
        self.label_baud = QtWidgets.QLabel(parent=Dialog)
        self.label_baud.setGeometry(QtCore.QRect(10, 0, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_baud.setFont(font)
        self.label_baud.setObjectName("label_baud")
        self.label_port = QtWidgets.QLabel(parent=Dialog)
        self.label_port.setGeometry(QtCore.QRect(10, 50, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_port.setFont(font)
        self.label_port.setObjectName("label_port")
        self.line_port = QtWidgets.QLineEdit(parent=Dialog)
        self.line_port.setGeometry(QtCore.QRect(10, 70, 251, 20))
        self.line_port.setAutoFillBackground(False)
        self.line_port.setText("3")
        self.line_port.setClearButtonEnabled(False)
        self.line_port.setObjectName("line_port")

        self.retranslateUi(Dialog)
        #self.buttonBox.clicked.connect()
        self.buttonBox.accepted.connect(lambda: self.buttonbox_ok_pressed(self.line_port.text(), self.line_baud.text())) # type: ignore
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Arduino Settings"))
        self.line_baud.setPlaceholderText(_translate("Dialog", "9600"))
        self.label_baud.setText(_translate("Dialog", "Serial Baud Rate"))
        self.label_port.setText(_translate("Dialog", "Arduino Port # (EX: COM3 = 3)"))
        self.line_port.setPlaceholderText(_translate("Dialog", "3"))

    def buttonbox_ok_pressed(self, port_number, baud):
        global arduino_port_name
        global baud_rate
        arduino_port_name = arduino_port(port_number)
        baud_rate = baud
        


