# Form implementation generated from reading ui file 'project.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from dhoc.angles.getazimuth import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line_lat = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.line_lat.setGeometry(QtCore.QRect(10, 40, 251, 20))
        self.line_lat.setText("")
        self.line_lat.setObjectName("line_lat")
        self.label_lat = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_lat.setGeometry(QtCore.QRect(10, 20, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_lat.setFont(font)
        self.label_lat.setObjectName("label_lat")
        self.label_lon = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_lon.setGeometry(QtCore.QRect(10, 80, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_lon.setFont(font)
        self.label_lon.setObjectName("label_lon")
        self.line_lon = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.line_lon.setGeometry(QtCore.QRect(10, 100, 251, 20))
        self.line_lon.setText("")
        self.line_lon.setObjectName("line_lon")
        self.line_planet = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.line_planet.setGeometry(QtCore.QRect(10, 150, 251, 20))
        self.line_planet.setText("")
        self.line_planet.setObjectName("line_planet")
        self.label_planet = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_planet.setGeometry(QtCore.QRect(10, 130, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_planet.setFont(font)
        self.label_planet.setObjectName("label_planet")
        self.button_findazimuth = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_findazimuth.setGeometry(QtCore.QRect(60, 190, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_findazimuth.setFont(font)
        self.button_findazimuth.setObjectName("button_findazimuth")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.button_findazimuth.clicked.connect((lambda: self.find_azimuth_clicked(self.line_lat.text(), self.line_lon.text(), self.line_planet.text())))


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DH Observatory Controller"))
        self.label_lat.setText(_translate("MainWindow", "Current Latitude (+ or -)"))
        self.label_lon.setText(_translate("MainWindow", "Current Longitude (+ or -)"))
        self.label_planet.setText(_translate("MainWindow", "Target Planet"))
        self.button_findazimuth.setText(_translate("MainWindow", "Find Azimuth"))

    def find_azimuth_clicked(self, lat, lon, planet):
        azimuth = get_azimuth(planet, float(lat), float(lon))
        return azimuth



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
